// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ChatbotAPI.Models;
//
//    var allianzDoctorApiResponse = AllianzDoctorApiResponse.FromJson(jsonString);

namespace ChatbotAPI.Models
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class AllianzDoctorApiResponse
    {
        [JsonProperty("results")]
        public List<Result> Results { get; set; }

        [JsonProperty("languages")]
        public List<string> Languages { get; set; }

        [JsonProperty("doctors")]
        public List<string> Doctors { get; set; }

        [JsonProperty("radius")]
        public long Radius { get; set; }
    }

    public partial class AllianzDoctorApiResponse
    {
        public static AllianzDoctorApiResponse FromJson(string json) => JsonConvert.DeserializeObject<AllianzDoctorApiResponse>(json, ChatbotAPI.Models.AllianzDoctorApiConverter.Settings);
    }
}
