// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ChatbotAPI.Models;
//
//    var mapsGeocodeApiResponse = MapsGeocodeApiResponse.FromJson(jsonString);

namespace ChatbotAPI.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class MapsGeocodeApiResponse
    {
        [JsonProperty("results")]
        public List<Result> Results { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }
    }

    public partial class Result
    {
        [JsonProperty("address_components")]
        public List<AddressComponent> AddressComponents { get; set; }

        [JsonProperty("formatted_address")]
        public string FormattedAddress { get; set; }

        [JsonProperty("geometry")]
        public Geometry Geometry { get; set; }

        [JsonProperty("place_id")]
        public string PlaceId { get; set; }

        [JsonProperty("types")]
        public List<string> Types { get; set; }
    }

    public partial class MapsGeocodeApiResponse
    {
        public static MapsGeocodeApiResponse FromJson(string json) => JsonConvert.DeserializeObject<MapsGeocodeApiResponse>(json, ChatbotAPI.Models.MapsGeocodeApiResponseConverter.Settings);
    }
}
