// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ChatbotAPI.Models;
//
//    var webhookResponseModel = WebhookResponseModel.FromJson(jsonString);

namespace ChatbotAPI.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class WebhookResponseModel
    {
        [JsonProperty("fulfillmentText")]
        public string FulfillmentText { get; set; }
        [JsonProperty("outputContexts", NullValueHandling = NullValueHandling.Ignore)]
        public List<OutputContext> OutputContexts { get; set; }

        [JsonProperty("followupEventInput", NullValueHandling = NullValueHandling.Ignore)]
        public FollowupEventInput FollowupEventInput { get; set; }
    }

    public partial class WebhookResponseModel
    {
        public static WebhookResponseModel FromJson(string json) => JsonConvert.DeserializeObject<WebhookResponseModel>(json, ChatbotAPI.Models.WebhookResponseModelConverter.Settings);
    }
}
